repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.80.0
  hooks:
    - id: terraform_fmt
      args:
        - --args=nomad-aws
        - --args=nomad-gcp
    - id: terraform_docs
      args:
        - --args=nomad-aws
        - --args=nomad-gcp
