repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.80.0
  hooks:
    - id: terraform_fmt
      # args:
      #   - nomad-aws
    # - id: terraform_docs
      # args:
      #     - --hook-config=--path-to-file=nomad-aws/README.md
