version: 2.1

orbs:
  shellcheck: circleci/shellcheck@2.2.0

workflows:
  version: 2
  terraform-validate:
    jobs:
      - shellcheck/check
      - format
      - check_docs
      - tfsec
      - validate:
          name: Nomad AWS basic
          tf_path: nomad-aws/examples/basic
          requires:
            - format
            - shellcheck/check
      - validate:
          name: Nomad GCP basic
          tf_path: nomad-gcp/examples/basic
          requires:
           - format
           - shellcheck/check

executors:
  deploy:
    resource_class: small
    docker:
      - image: cimg/deploy:2025.01
  tfsec:
    resource_class: small
    docker:
      - image: aquasec/tfsec:v1.28
  linux-vm:
    machine:
      image: ubuntu-2004:current
      resource_class: small

jobs:
  validate:
    executor: deploy
    parameters:
      tf_path:
        type: string
    working_directory: << parameters.tf_path >>
    steps:
      - checkout
      - run: terraform init
      - run: terraform validate

  format:
    executor: deploy
    steps:
      - checkout
      - run: terraform fmt -check -diff -recursive

  tfsec:
    executor: tfsec
    steps:
      - checkout
      - run: tfsec .

  check_docs:
    executor: linux-vm
    steps:
      - checkout
      - run:
          name: Generate Docs
          command: make docs
      - run:
          name: Check if docs need to be updated
          command: |
            set +eo pipefail
            git diff --quiet nomad-aws/README.md nomad-gcp/README.md
            if [ $? -ne 0 ]; then
              echo "There have been docs changes. Please run the 'make docs' command locally."
              exit 1
            else
              echo "Docs are up to date. No changes required."
            fi
