version: 2.1

orbs:
  shellcheck: circleci/shellcheck@2.2.0

workflows:
  version: 2
  terraform-validate:
    jobs:
      - shellcheck/check
      - format
      - check_docs
      - tfsec
      - validate:
          name: Nomad AWS basic
          tf_path: nomad-aws/examples/basic
          requires:
            - format
            - shellcheck/check
      - validate:
          name: Nomad GCP basic
          tf_path: nomad-gcp/examples/basic
          requires:
           - format
           - shellcheck/check

executors:
  tfsec:
    resource_class: small
    docker:
      - image: cimg/base:current
  default:
    resource_class: small
    docker:
      - image: hashicorp/terraform:1.4.6
jobs:
  validate:
    executor: default
    parameters:
      tf_path:
        type: string
    steps:
      - checkout

      - run:
          name: terraform init
          working_directory: << parameters.tf_path >>
          command: terraform init

      - run:
          name: terraform validate
          working_directory: << parameters.tf_path >>
          command: terraform validate

  format:
    executor: default
    steps:
      - checkout

      - run:
          name: terraform fmt
          command: terraform fmt -check -diff -recursive

  tfsec:
    executor: tfsec
    steps:
      - checkout
      - run:
          name: install tfsec
          command: curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      - run:
          name: run tfsec
          command: tfsec .

  check_docs:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apk add --update-cache --upgrade curl
      - run:
          name: Install terraform-docs
          command: |
            TERRAFORM_DOCS_VERSION="v0.16.0"
            curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/$TERRAFORM_DOCS_VERSION/terraform-docs-$TERRAFORM_DOCS_VERSION-$(uname)-amd64.tar.gz
            tar -xzf terraform-docs.tar.gz
            chmod +x terraform-docs
            mv terraform-docs /usr/local/bin/terraform-docs
      - run:
          name: Generate Docs
          command: |
            cd scripts
            sh generate-docs.sh
      - run:
          name: Check if docs need to be updated
          command: |
            set +eo pipefail
            git diff --quiet nomad-aws/README.md nomad-gcp/README.md
            if [ $? -ne 0 ]; then
              echo "There have been docs changes. Please run the 'make docs' command locally."
              exit 1
            else
              echo "Docs are up to date. No changes required."
            fi
